#
# Jekyll configuration
#
destination: ./_site
permalink:   pretty
#paginate:    20
lsi:         false
#lsi:         false
pygments:    true
#markdown:    maruku
markdown:    rdiscount

baseurl: /

relative_permalinks: true

#
# Site configuration
#
url:          http://www.nata2.org
title:        "Harper Reed's blog archive "
description:  I blogged from 2000 to 2012. I don't do it very often any longer. This is my archive.  
author:       Harper Reed # atom.xml: Name of website's author
email:        harper@nata2.org # atom.xml: Author email
analytics_id: UA-70650-9 # Google Analytics ID: UA-xxx-xxx
media_version: 9
media_server: "" #http://media.nata2.org
