# Site settings

email: harper@nata2.org
description: > # this means to ignore newlines until "baseurl:"
    The writing of Harper Reed. 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://harper.blog" # the base hostname & protocol for your site

#social
twitter_username: harper
github_username:  harperreed
pgpkey:  harperreed.pgp
medium_username: harper
copyright_year: 2016
cachebuster: harperreed-2016-09-7

title: Harper Reed &middot; the writing of Harper Reed
rss_title: Harper Reed - the writing of Harper Reed

# Build settings
markdown:   kramdown
exclude:    ['Makefile','s3_website.yml','s3_website.example.yml','README.md','.gitignore', 'node_modules']
permalink:  pretty
paginate: 5

gems: [jekyll-paginate]

sass:
    style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      category: "writing"

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock