#
# Jekyll configuration
#
#destination: ./_site
auto:        false
lsi:         true # better related posts
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   pretty
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex

#
# Site configuration
#
url:          http://www.nata2.org
title:        "Harper Reed: Tech, Mobile, Yo-yoing and Death Metal"
description:  Software, PHP, MySQL, XMPP, Hacking, Baphomet
author:       Harper Reed # atom.xml: Name of website's author
email:        harper@nata2.org # atom.xml: Author email
analytics_id: UA-70650-9 # Google Analytics ID: UA-xxx-xxx
